#!/bin/sh

echo "nsd: stopping ..."
pkill nsd

echo "nsd: redeploy from persistent /etc/nsd to /var/nsd ..."
for view in internal external; do
	rm -rf /tmp/var/nsd-$view
	cp -R /etc/nsd-$view /tmp/var/nsd-$view
	cp -R /etc/nsd-common/zones/* /tmp/var/nsd-$view/zones/.
	chown -R root:_nsd /tmp/var/nsd-$view/{db,etc,run}
	chmod 0770 /tmp/var/nsd-$view/{db,run,run/xfr}
done

echo "nsd: restarting ..."
/usr/sbin/nsd -c /var/nsd-internal/etc/nsd.conf
/usr/sbin/nsd -c /var/nsd-external/etc/nsd.conf
